# Configuración básica
quarkus.http.port=8080
quarkus.application.name=eventos-venues-api

# OpenAPI/Swagger
quarkus.smallrye-openapi.path=/swagger
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger-ui

# Perfiles
%dev.quarkus.log.level=DEBUG
%test.quarkus.log.level=INFO
